from flask import Flask, request, jsonify, render_template
import speech_recognition as sr
from rapidfuzz import process
from pydub import AudioSegment
from flask_cors import CORS
import os

app = Flask(__name__)
CORS(app)

# Sample dataset
dataset = ['hanana', 'Banana', 'karl', 'carl', 'jira', 'jeera',
'Paracetamol 500',
'Ibuprofen 400',
'Aspirin 325',
'Ciprofloxacin 500',
'Metformin 850',
'Amoxicillin 250',
'Azithromycin 500',
'Clindamycin 300',
'Doxycycline 100',
'Hydroxychloroquine 200',
'Loratadine 10',
'Cetirizine 10',
'Simvastatin 40',
'Atorvastatin 20',
'Pantoprazole 40',
'Omeprazole 20',
'Lisinopril 10',
'Amlodipine 5',
'Metoprolol 50',
'Losartan 50',
'Furosemide 40',
'Prednisolone 5',
'Levothyroxine 50',
'Bupropion 150',
'Trazodone 50',
'Venlafaxine 75',
'Gabapentin 300',
'Clonazepam 0.5',
'Alprazolam 1',
'Warfarin 5',
'Acetaminophen',
'Ibuprofen',
'Aspirin',
'Ciprofloxacin',
'Metformin',
'Amoxicillin',
'Azithromycin',
'Clindamycin',
'Doxycycline',
'Hydroxychloroquine',
'Loratadine',
'Cetirizine',
'Simvastatin',
'Atorvastatin',
'Pantoprazole',
'Omeprazole',
'Lisinopril',
'Amlodipine',
'Metoprolol',
'Losartan',
'Furosemide',
'Prednisolone',
'Levothyroxine',
'Bupropion',
'Trazodone',
'Venlafaxine',
'Gabapentin',
'Clonazepam',
'Alprazolam',
'Warfarin',
'Citalopram',
'Escitalopram',
'Sertraline',
'Fluoxetine',
'Paroxetine',
'Quetiapine',
'Risperidone',
'Olanzapine',
'Ziprasidone',
'Aripiprazole',
'Glimepiride',
'Glyburide',
'Sitagliptin',
'Vildagliptin',
'Linagliptin',
'Tramadol',
'Morphine',
'Codeine',
'Fentanyl',
'Methadone',
'Montelukast',
'Zafirlukast',
'Theophylline',
'Aminophylline',
'Dulaglutide',
'Semaglutide',
'Exenatide',
'Liraglutide',
'Insulin',
'Glucagon',
'Ranitidine',
'Cimetidine',
'Famotidine',
'Nizatidine',
'Sucralfate',
'Amul Butter one packet',
'Aashirvad Aata five bags',
'Britannia 50 50 five packets',
'Maggi noodles ten packets',
'Tata Tea premium one box',
'Red Label Tea two packets',
'Basmati rice five kg',
'Patanjali Honey one bottle',
'Parle-G biscuits one pack',
'Fanta two bottles',
'Pepsi one bottle',
'Lays chips three packets',
'Kellogg\'s Cornflakes one box',
'Mother Dairy Milk three litres',
'Dove soap four bars',
'Lux soap two bars',
'Head and Shoulders shampoo one bottle',
'Vicks Vaporub one jar',
'Sunsilk shampoo two bottles',
'Surf Excel washing powder one box',
'Wheel washing powder two packets',
'Tata Salt two packets',
'Saffola oil one litre',
'Fortune oil two litres',
'Del Monte tomato ketchup one bottle',
'Nescafe coffee one jar',
'Britannia Good Day two packets',
'Amul Cheese slices one packet',
'Maggi Masala one box',
'Coca-Cola two bottles',
'Frooti mango drink two packs',
'Bisleri water three bottles',
'Kissan Jam one bottle',
'Colgate Toothpaste one tube',
'Sensodyne Toothpaste one tube',
'Dabur Amla Hair Oil one bottle',
'Santoor soap two bars',
'Ponds cream one jar',
'Axe body spray one can',
'Fair & Lovely cream one tube',
'Nivea cream one jar',
'Head and Shoulders shampoo one bottle',
'Pepsodent Toothpaste one tube',
'Vaseline lotion one bottle',
'Tata Tea Gold one box',
'Britannia Treat one packet',
'Lays salted chips two packets',
'Coca-Cola six bottles',
'Cadbury Dairy Milk chocolate one bar',
'Tata Salt one packet',
'Bovonto juice one bottle',
'Britannia Milk Bikis one pack',
'Amul Ghee one litre',
'Godrej Hair Color one box',
'Madhur Sugar five kg',
'Tata Biscuits one pack',
'Red Label Tea one packet',
'Aashirvad Salt one packet',
'MTR Sambar Powder one packet',
'Tata Tea one box',
'Maggi Instant Noodles three packets',
'Britannia Little Hearts one packet',
'Lays Classic chips one packet',
'Amul Milk two litres',
'Kissan Tomato Ketchup one bottle',
'Sundrop oil one litre',
'Patanjali Atta one kg',
'Saffola Masala Oats one pack',
'Dove shampoo two bottles',
'Sunsilk conditioner one bottle',
'Madhuri Vanaspati one kg',
'Pepsi Black one bottle',
'Gujarat Ghee one kg',
'Amul Paneer one block',
'Kellogg\'s Special K one box',
'Parle-G biscuits five packets',
'Amul Fresh Cream one packet',
'Maggi noodles one packet',
'MTR Rasam Powder one packet',
'Britannia Cream Biscuits one pack',
'Britannia Cake one packet',
'Vicks Vaporub one bottle',
'Tata Tea Chakra Gold one box',
'Fortune Mustard Oil one litre',
'Tata Sampann Toor Dal one packet',
'Amul Cheese one packet',
'Chings Secret one pack',
'MTR Gulab Jamun Mix one packet',
'Dabur Honey one bottle',
'Patanjali Soap two bars',
'Aashirvad Basmati Rice one kg',
'Britannia Rusk one packet',
'Nestle Everyday Tea Creamer one tin',
'Nestle Nescafe Classic one jar',
'Haldiram Snacks one pack',
'Maggie Atta Noodles one packet',
'Kissan Jam two jars',
'Tata Tea Gold one packet',
'Sundrop Peanut Butter one jar',
'Saffola Masala Oats one box',
'Britannia Milk Cake one box',
'Chings Sauces one bottle',
'Tata Tea Gold Tea Bags one box',
'Lux Soap one bar',
'Dove soap one bar',
'Axe body spray one can',
'Dove body wash one bottle',
'Maggi Instant Soup one packet',
'Pepsi Cola one can',
'Fanta Orange one can',
'Saffola Olive Oil one litre',
'Tata Sampann Ghee one litre',
'Tata Salt one kg',
'Mother Dairy Cheese one packet',
'Britannia Milk Biscuits one packet',
'Fortune Rice Bran Oil one litre',
'Haldiram Kaju one pack',
'Tata Tea Premium one box',
'Fortune Soya Oil one litre',
'Patanjali Rajma one pack',
'Britannia NutriChoice biscuits one pack',
'Nestle Munch one pack',
'Parle Krackjack biscuits one pack',
'Amul Cheese spread one pack',
'Dabur Real Fruit Juice one pack',
'Fanta Grape one bottle',
'Britannia Little Hearts biscuits one packet',
'Nestle Milo one tin',
'Parle Monaco one packet',
'Madhur Ghee one kg',
'Britannia NutriChoice biscuits one packet',
'Red Label Tea one packet',
'Sundrop Oil one bottle',
'Bovonto Grape juice one bottle',
'Britannia Bourbon biscuits one packet',
'Britannia Milk Chocolate one bar',
'Kissan Mango Jam one jar',
'Sundrop Olive Oil one litre',
'Del Monte pasta one packet',
'Fanta Soft Drink one can',
'Parle-G biscuit pack one',
'Coca Cola 600ml',
'Pepsi 600ml',
'Tata Sampann Toor Dal one packet',
'Patanjali Aloe Vera Gel one bottle',
'Britannia Good Day biscuits one pack',
'Maggi Instant Noodles one pack',
'Coca Cola two litres',
'Cadbury Oreo biscuit pack',
'Britannia Milk Rusk one packet',
'Nestle Nescafe one jar',
'Tata Tea Gold Tea Bags one box',
'Haldiram\'s Bhel Puri one pack',
'Tata Salt one packet',
'Saffola Oats one pack',
'Tata Sampann Chana Dal one packet',
'Parle G Biscuit one packet',
'Dove Shampoo one bottle',
'Kissan Mango Jam one bottle',
'MTR Vegetable Biryani one pack',
'Nestle Munch chocolate one pack',
'Tata Salt one packet',
'Aashirvad Atta one kg',
'Amul Butter one packet',
'Red Label Tea one pack',
'Britannia Bourbon Biscuits one pack',
'Del Monte Tomato Ketchup one bottle',
'Aashirvad Salt one packet',
'Sundrop Peanut Butter one jar',
'Fanta one bottle',
'Saffola Oats one box',
'Parle-G Biscuit Pack one',
'Cadbury Dairy Milk one bar',
'Nescafe Classic one jar',
'Britannia Rusk one pack',
'Patanjali Honey one jar',
'Tata Tea one box',
'Lays Chips one pack',
'Maggi Instant Noodles one pack'
]

recognizer = sr.Recognizer()

# Function to get suggestions using fuzzy matching
def get_suggestions(input_word, dataset):
    suggestions = process.extract(input_word, dataset, limit=5)
    print(suggestions)
    return [word for word, score, _ in suggestions if score > 60]
    
@app.route('/')
def index():
    return render_template('index.html')

@app.route('/voice-input', methods=['POST'])
def voice_input():
    if 'audio' not in request.files:
        return jsonify({'error': 'No audio file provided'}), 400

    audio_file = request.files['audio']
    try:
        # Save the uploaded audio file
        audio_path = 'temp_audio.webm'
        wav_path = 'temp_audio.wav'
        audio_file.save(audio_path)

        # Convert WebM/Opus to WAV using pydub
        audio = AudioSegment.from_file(audio_path, format='webm')
        audio.export(wav_path, format='wav')

        # Use SpeechRecognition to process the converted WAV file
        with sr.AudioFile(wav_path) as source:
            audio_data = recognizer.record(source)
            print(audio_data)
            text = recognizer.recognize_google(audio_data)
            print(f"Recognized Text: {text}")

            # Get suggestions
            suggestions = get_suggestions(text, dataset)
            return jsonify({'suggestions': suggestions})

    except Exception as e:
        print(f"Error: {e}")
        return jsonify({'error': str(e)}), 500

    finally:
        # Clean up temporary files
        if os.path.exists(audio_path):
            os.remove(audio_path)
        if os.path.exists(wav_path):
            os.remove(wav_path)

if __name__ == '__main__':
    app.run(debug=True)
